// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkk-SWZDgva_eMtxF737l9d9wiuaOfAi8',
    appId: '1:721391016471:web:66f48aca45d9421390da52',
    messagingSenderId: '721391016471',
    projectId: 'e-learning-e341d',
    authDomain: 'e-learning-e341d.firebaseapp.com',
    storageBucket: 'e-learning-e341d.appspot.com',
    measurementId: 'G-F63FQ84158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42HWceQWj1grQS5micbVNM6VRGw9wrao',
    appId: '1:721391016471:android:318813e3004862cd90da52',
    messagingSenderId: '721391016471',
    projectId: 'e-learning-e341d',
    storageBucket: 'e-learning-e341d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCooQn85OUy8zUsDzk4FeaKw0Lh3yg-t7M',
    appId: '1:721391016471:ios:659764fa9ba2e04b90da52',
    messagingSenderId: '721391016471',
    projectId: 'e-learning-e341d',
    storageBucket: 'e-learning-e341d.appspot.com',
    iosBundleId: 'com.example.elearningproject',
  );
}
